### ISSUE TITLE
Allow functions and definitions in @media and @if / @elseif

### ISSUE THREAD

**Issue by Yannic** [Yannic/closure-stylesheets#1]
See #80

`foo.gss`:
```css
@def FOO 100px;

@media (min-width: FOO) {
  .bar {
    color: red;
  }
}
```
 command:
` java -jar closure-stylesheets-1.5.0-SNAPSHOT-jar-with-dependencies.jar foo.gss`

output:
```css
@media (min-width: FOO) {
  .bar{
    color: red;
  }
}
```

expected output:
```css
@media (min-width: 100px) {
  .bar{
    color: red;
  }
}
```
